### ISSUE TITLE
I need a way to read messages of postcss

### ISSUE THREAD

**Issue by gucong3000** [postcss/gulp-postcss#105]
In my case, I need to read messages of gulp plugin, and show them in GUI.

I write a module, to read messages of `gulp-eslint` or `gulp-jshint`, both of them are have way to read output.

That is code from `gulp-eslint`, it is output result as `file.eslint`:

```javascript
		file.eslint = verify(file.contents.toString(), filePath);
```

https://github.com/adametry/gulp-eslint/blob/master/index.js#L70

That is code from `gulp-jshint`, it is output result as `file.jshint`:
```javascript
      // get or create file.jshint, we will write all output here
      var out = file.jshint || (file.jshint = {});
```
https://github.com/spalger/gulp-jshint/blob/master/src/lint.js#L90

That is what I want: #106

**Comment by gucong3000** [comment]
`gulp-babel` uses a similar strategy:

```javascript
file.babel = res.metadata;
```
https://github.com/babel/gulp-babel/blob/master/index.js#L49

**Comment by w0rm** [comment]
I am against of adding anything into the gulp file object, because the file may be shared between multiple plugins and each plugin won't keep this info up to date. 

sourcemaps is the exception, and there are so many issues with it. 

If you need to read messages from postcss, you can create your own reporter plugin for postcss.

**Comment by gucong3000** [comment]
These gulp plugins have interfaces to get messages.
I really need this interface like them.

[gulp-csslint](https://github.com/lazd/gulp-csslint)
[eclint](https://github.com/jedmao/eclint)
[gulp-eslint](https://github.com/adametry/gulp-eslint)
[gulp-htmlhint](https://github.com/bezoerb/gulp-htmlhint)
[gulp-jscs](https://github.com/jscs-dev/gulp-jscs)
[gulp-jshint](https://github.com/spalger/gulp-jshint)
[gulp-tslint](https://github.com/panuhorsmalahti/gulp-tslint)

I will use it in my plugin [gulp-reporter](https://github.com/gucong3000/gulp-reporter)
Please reconsider my request
