### ISSUE TITLE
Cant preserve the previous source map?

### ISSUE THREAD

**Issue by creeperyang** [postcss/gulp-postcss#109]
It seems `gulp-postcss` will lose previous source map:

```js
var init = sourceMaps.init({loadMaps: true})
var css = postcss(
  [ doubler, doubler ]
)
init.pipe(css)

// Assume we have a file with source map
  var file = new gutil.File({
    base: __dirname,
    path: __dirname + '/style/all.css',
    contents: new Buffer(`body {color: #333;}\nbody {margin: 0;}\n/*# sourceMappingURL=${
      'data:application/json;charset=utf8;base64,' + new Buffer(JSON.stringify({
        version: 3,
        sources: ['style/a.css', 'style/b.css'],
        names: [],
        mappings: 'AAAA;AACA;ACDA;AACA',
        file: 'style/all.css',
        sourcesContent: ['body {color: #333;}\n', 'body {margin: 0;}\n']
      })).toString('base64')
    } */`)
  })

init.write(file)
init.end()
/*previous source map:
{
	"version": 3,
	"sources": [
		"style/a.css",
		"style/b.css"
	],
	"names": [],
	"mappings": "AAAA;AACA;ACDA;AACA",
	"file": "style/all.css",
	"sourcesContent": [
		"body {color: #333;}\n",
		"body {margin: 0;}\n"
	]
}*/


// After gulp-postcss processed, the new source map is like:
{ version: 3,
  sources: [ 'style/style/a.css' ],
  names: [],
  mappings: 'AAAA,MAAA,YAAA,YAAA,YAAA,YAAA,CAAA;AACA,MAAA,UAAA,UAAA,UAAA,UAAA,CAAA',
  file: 'style/all.css',
  sourcesContent: [ 'body {color: #333;}\n' ] }
```

It lose one `source`, and the other `source` get **wrong** path.

**Comment by w0rm** [comment]
I think that the original input data is corrupted. Try to write it to the disk and open in the browser. Source `b` is not used:

![screen shot 2017-01-24 at 13 27 38](https://cloud.githubusercontent.com/assets/43472/22247257/2efabb26-e239-11e6-99c1-314f748100d7.png)

As for the path modification, it happened before `gulp-postcss` as you can see in `previous source map`.

**Comment by creeperyang** [comment]
I'm not sure, but I saw differences after write it to disk.

<img width="941" alt="2017-01-24 8 46 50" src="https://cloud.githubusercontent.com/assets/8046480/22247740/4aa7f7b6-e276-11e6-807a-83c374e3c9dd.png">


And the css:

```css
body {color: #333;}

body {margin: 0;}

/*# sourceMappingURL=all.css.map */
```

```js
{
    "version": 3,
    "sources": ["style/a.css", "style/b.css"],
    "names": [],
    "mappings": "AAAA;AACA;ACDA;AACA",
    "file": "all.css",
    "sourcesContent": ["body {color: #333;}\n", "body {margin: 0;}\n"],
    "sourceRoot": "../../demo/assets"
}
```

**Comment by w0rm** [comment]
@creeperyang this looks different from your original example, where you had the source map base64 encoded and included in the css file.

**Comment by creeperyang** [comment]
Assume the `all.css` (from `a.css` and `b.css`) embed the source map, it has a correct mapping to its source `a.css` and `b.css`.

And then I want process the `all.css` with `postcss` (`gulp-postcss` here), but the `gulp-postcss` will drop the original mapping. 

That's the point.

See code below:

```js
it('should correctly generate relative source map', function (cb) {
  var prevMap = {
    version: 3,
    sources: ['style/a.css', 'style/b.css'],
    names: [],
    mappings: 'AAAA;AACA;ACDA;AACA',
    file: 'style/all.css',
    sourcesContent: ['body {color: #333;}\n', 'body {margin: 0;}\n']
  }
  var comment = `/*# sourceMappingURL=data:application/json;charset=utf8;base64,${
    new Buffer(JSON.stringify(prevMap)).toString('base64')
  } */`

  var init = sourceMaps.init({loadMaps: true})
  var css = postcss([])

  init.pipe(css)

  css.on('data', function (file) {
    console.log('final map:', file.sourceMap)
   /*
    final map: { version: 3,
  sources: [ 'style/style/a.css' ],
  names: [],
  mappings: 'AAAA,MAAA,YAAA,CAAA;AACA,MAAA,UAAA,CAAA',
  file: 'style/all.css',
  sourcesContent: [ 'body {color: #333;}\n' ] }
  // lost original mappings
   */
    cb()
  })

  init.write(new gutil.File({
    base: __dirname,
    path: __dirname + '/style/all.css',
    // The contents has everything, `gulp-postcss` should preserve the original mappings.
    contents: new Buffer(`body {color: #333;}\nbody {margin: 0;}\n${comment}`)
  }))

  init.end()

})
```

**Comment by w0rm** [comment]
That's the point, I don't want to assume.

```js
new Buffer(`body {color: #333;}\nbody {margin: 0;}\n/*# sourceMappingURL=${
      'data:application/json;charset=utf8;base64,' + new Buffer(JSON.stringify({
        version: 3,
        sources: ['style/a.css', 'style/b.css'],
        names: [],
        mappings: 'AAAA;AACA;ACDA;AACA',
        file: 'style/all.css',
        sourcesContent: ['body {color: #333;}\n', 'body {margin: 0;}\n']
      })).toString('base64')
    } */`)
```

I wrote this file to the filesystem and opened it in the browser and it did not work for me. If you want help, please set up a test project that reproduces the whole issue.

**Comment by creeperyang** [comment]
This is a test project. <https://github.com/creeperyang/gulp-postcss/tree/test/test-proj>

`all.css` is my input data, and the generated `result.css` has correct mappings.

So you are right.

However, the generated `result.css.map`'s `sources` is incorrect.

**Comment by w0rm** [comment]
If you output the result from the `init` stream it looks weird:

```
{ version: 3,
  sources: [ 'assets/style/style/a.css', 'assets/style/style/b.css' ],
  names: [],
  mappings: 'AAAA;AACA;ACDA;AACA',
  file: 'assets/style/all.css',
  sourcesContent: [ 'body {color: #333;}\n', 'body {margin: 0;}\n' ],
  sourceRoot: '../../demo/assets',
  preExistingComment: 'all.css.map' }
```

**Comment by w0rm** [comment]
So, I've reviewed your example. First, the result source map includes both sources correctly. It's just that their paths are incorrect. I've written out the steps in a table:

<img width="972" alt="screen shot 2017-01-28 at 22 49 03" src="https://cloud.githubusercontent.com/assets/43472/22400081/042ba380-e5ac-11e6-860a-d0238d1b0904.png">

So you can see that the sources are already wrong, when loaded with gulp-sourcemaps.

And then they are modified again by `vinyl-sourcemaps-apply`, that seems to concatenate `sourceRoot` with sources (gulp-postcss uses it just as any other plugin that works with gulp-sourcemaps), so `../../demo/assets` + `assets/style/style/a.css` becomes `../../demo/assets/assets/style/style/a.css`.
