### ISSUE TITLE
Support for `*.vue` and HTML file.

### ISSUE THREAD

**Issue by gucong3000** [postcss/gulp-postcss#119]
I created a module for `postcss` to support HTML. [postcss-html](https://github.com/gucong3000/postcss-html)

If I can use `gulp-postcss` in this way, that would be great:

```js
gulp.src("src/**/*.html")
  .pipe(postcss([stylelint, autoprefixer]))
```

I'd like to push an PR for this.

**Comment by w0rm** [comment]
@gucong3000 won't it work if you pass the syntax option?

```
var gulp = require('gulp');
var syntax = require('postcss-html');
gulp.task('default', function () {
    return gulp.src('index.html')
       .pipe(postcss(plugins, { 
           syntax: syntax({
               css: require('postcss'),
               less: require('postcss-less'),
               scss: require('postcss-scss')
           })
	     }))
       .pipe(gulp.dest('out'));
});
```

**Comment by gucong3000** [comment]
I hope that, no matter which kind file to use, `gulp-postcss` will work properly without user - defined options.

**Comment by w0rm** [comment]
If you don't like explicit configuration, `gulp-postcss` supports `postcss.config.js` that is a unified way to configure PostCSS and is used by other loaders.

**Comment by gucong3000** [comment]
#121

**Comment by w0rm** [comment]
As I have mentioned previously, I am against implicit configuration magic and dependency on the syntax plugins. `gulp-postcss` is a thin runner, its options should be as close as possible to postcss options.

**Comment by gucong3000** [comment]
It is so thin.
