### ISSUE TITLE
gulp-postcss + csscomb

### ISSUE THREAD

**Issue by Alecto** [postcss/gulp-postcss#146]
Please tell me if there is a csscomb plugin that works with gulp-postcss?
I tried https://www.npmjs.com/package/csscomb and https://www.npmjs.com/package/gulp-csscomb they do not work with gulp-postcss.

**Comment by w0rm** [comment]
Because csscomb is not a postcss plugin, it cannot work with postcss and thus it cannot work with gulp-postcss. But because gulp-csscomb exists, I believe it should be possible to pipe the file through gulp-postcss followed by gulp-csscomb.

```js
return gulp.src('src/*.css')
   .pipe(postcss(...))
   .pipe(csscomb(...))
```
