### ISSUE TITLE
Gulp is out of date. Following the https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5 to fix

### ISSUE THREAD

**Issue by gaulltimothy** [postcss/gulp-postcss#148]
gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
+ gulp-update@0.0.2

gulp-postcss@6.1.1
│ └── gulp-util@3.0.8

**Comment by w0rm** [comment]
`6.1.1` is not the latest version of gulp-postcss. We've already dropped gulp-util dependency https://github.com/postcss/gulp-postcss/pull/137.
