### ISSUE TITLE
Logging warnings when NODE_ENV=development

### ISSUE THREAD

**Issue by buhlahkay** [postcss/gulp-postcss#149]
When I set process.env.NODE_ENV to anything other than "production" I get a ton of logs of this warning:

`You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.`

Comes from here: https://github.com/postcss/postcss/blob/master/lib/processor.es6#L99

Is there a way to silence the warnings? It looks like everything's still getting parsed correctly, I just don't want my terminal getting clogged up with all these warnings.

**Comment by mcguffin** [comment]
For me this happens every time a scss `@import` statement is parsed. 
Tracing it down takes me to one of the dependencies of `precess`, which calls `postcss()` without any configuration: https://github.com/jonathantneal/postcss-advanced-variables/blob/master/src/lib/transform-import-atrule.js#L75

**Comment by w0rm** [comment]
Hi, if this is still happening, maybe ask in the postcss repo, as the log entry is coming from there. gulp-postcss is a thin wrapper that runs postcss and doesn't control its console output.
