### ISSUE TITLE
Security vulnerability in js-yaml

### ISSUE THREAD

**Issue by UncertainConstraint** [postcss/gulp-postcss#153]
`yarn audit` reports a security issue **js-yaml**:

| moderate | Denial of Service |
|--|--|
| Package | js-yaml |
| Patched in | >=3.13.0 |
| Dependency of | gulp-postcss |
| Path | gulp-postcss > postcss-load-config > cosmiconfig > js-yaml | 
| More info | https://www.npmjs.com/advisories/788 |

**Comment by jonathantneal** [comment]
I’ve updated dependencies here, but this looks like an issue for https://github.com/michael-ciniawsky/postcss-load-config
