### ISSUE TITLE
False positive invalid syntax error

### ISSUE THREAD

**Issue by tschallacka** [postcss/gulp-postcss#157]
gulp-postcss gives the following warning

```
[11:30:07] CssSyntaxError in plugin "gulp-postcss"
Message:
    C:\Massweb\exit-reizen\csstemplates\template\newstyle\npm\style.css:24703:59: Unclosed string

  24701 | }
  24702 | section.tripfilter .container.no-padding div[class^="col-"],
> 24703 | section.tripfilter .container.no-padding div[class*=" col-"] {
        |                                                           ^
  24704 |   padding: 0px !important;
  24705 | }

```

Which is false. The strings are closed. No idea why it matches on this, and I can fix the css somewhat for this particularly hacked together code, but this shouldn't trigger a warning.

The less that caused this error:

    section.tripfilter .container {
		&.no-padding {
			div { 
				 
				 &[class^="col-"],
				 &[class*=" col-"] {
					padding:0px !important;
				} 
			}
		}
	}

Even when I comment it, it still triggers the error

    section.tripfilter .container {
		&.no-padding {
			div { 
				/* 
				 * &[class^="col-"],
				 * &[class*=" col-"] {
				 *	padding:0px !important;
				} */
			}
		}
	}

```
  [12:17:32] CssSyntaxError in plugin "gulp-postcss"
Message:
    C:\Massweb\exit-reizen\csstemplates\template\newstyle\npm\style.css:24709:23: Unclosed string

  24707 |   /*
  24708 |                                * &[class^="col-"],
> 24709 |                                * &[class*=" col-"] {
        |                                                 ^
  24710 |                                *      padding:0px !important;
  24711 |                               } */


```

I was able to fix it by putting a comment stripper before pushing this through postcss, but honestly, a quote in a comment, or commented code should not trigger an error.

**Comment by w0rm** [comment]
This is most likely related to PostCSS itself, `gulp-postcss` is just a wrapper that runs [PostCSS](https://github.com/postcss/postcss).
