### ISSUE TITLE
Error in plugin "gulp-postcss"

### ISSUE THREAD

**Issue by mailtorajatsingh** [postcss/gulp-postcss#159]
getting this issue in building css .

`AMAC02XF2DXJG5J:build-setup rajat.c.singhaccenture.com$ gulp styles
[01:32:51] Using gulpfile ~/Local Sites/cp-unique-convent-school/app/public/build-setup/gulpfile.js
[01:32:51] Starting 'styles'...
Error in plugin "gulp-postcss"
Message:
    Failed to find 'normalize.css'
  in [
    /Users/rajat.c.singhaccenture.com/Local Sites/cp-unique-convent-school/app/public/wp-content/themes/uniqueconventschool/css
  ]
Details:
    fileName: /Users/rajat.c.singhaccenture.com/Local Sites/cp-unique-convent-school/app/public/wp-content/themes/uniqueconventschool/css/style.css

Stack:
Error: Failed to find 'normalize.css'
  in [
    /Users/rajat.c.singhaccenture.com/Local Sites/cp-unique-convent-school/app/public/wp-content/themes/uniqueconventschool/css
  ]
    at /Users/rajat.c.singhaccenture.com/Local Sites/cp-unique-convent-school/app/public/build-setup/node_modules/postcss-import/lib/resolve-id.js:35:13
[01:32:51] Finished 'styles' after 26 ms
`

import statements in my source file which  i am trying to compile ..

@import "normalize.css";
@import "slick-carousel/slick/slick.css";

**Comment by w0rm** [comment]
`gulp-postcss` doesn't handle imports, it only runs PostCSS on the top file, this is most likely related to a PostCSS plugin that you're using. Looks like it cannot find the file that is being imported.
