### ISSUE TITLE
Extension css for output

### ISSUE THREAD

**Issue by alkorlos** [postcss/gulp-postcss#163]
Thank you for your open source.
Official twitter PostCSS advises "If you need file extension for PostCSS based sources, we suggest .pcss" https://twitter.com/PostCSS/status/661645290622083073
Is it possible using gulp-postcss to have input files in .postcss format and get .css output without additional libraries like gulp-rename? Automatic renaming would be handy.

**Comment by w0rm** [comment]
I would rather pipe the result through `gulp-rename` for more explicit transformation.

According to [gulp plugin guidelines](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md#guidelines)

> Your plugin should only do one thing, and do it well.

For example, renaming affects [the source map too](https://github.com/hparra/gulp-rename/blob/master/index.js#L59), if we missed this, it could have caused unexpected behavior. `gulp-rename` is battle tested and there is no need to replicate its functionality.

If you still find this confusing, a PR to update the readme with how to use `gulp-postcss` and `gulp-rename` together to support `.postcss` extension is welcome!

**Comment by alkorlos** [comment]
Thank you for the answer!

I didn't think it was done on purpose. Gulp plugins for `nunjucks`, `pug`, `scss`, `less `etc. change the extension ourselves. Especially considering that in `gulp 4` automatic renaming works fine (if I get right), for example in gulp-postcss this is done by adding `file.extname = '.css'` on line 50.

So yes, still find this confusing. Updatingthe readme to make it clearer.
