### ISSUE TITLE
PostCSS plugin autoprefixer requires PostCSS 8. Update PostCSS or downgrade this plugin

### ISSUE THREAD

**Issue by Alecto** [postcss/gulp-postcss#165]
Today, after updating plugins, I got the following error:
**PostCSS plugin autoprefixer requires PostCSS 8. Update PostCSS or downgrade this plugin**

package.json
```
{
  "name": "gulp",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "autoprefixer": "^10.0.0",
    "browser-sync": "^2.26.12",
    "css-mqpacker": "^7.0.0",
    "cssnano": "^4.1.10",
    "gulp": "^4.0.2",
    "gulp-csscomb": "^3.1.0",
    "gulp-notify": "^3.2.0",
    "gulp-postcss": "^8.0.0",
    "gulp-rename": "^2.0.0",
    "gulp-sass": "^4.1.0",
    "sort-css-media-queries": "^1.5.0"
  }
}
```

![image](https://user-images.githubusercontent.com/8464662/93666000-6166ac80-fa83-11ea-8a85-45f3c3635ca8.png)

**Comment by hungvq-0871** [comment]
Got the same problem too
Just reverting the **autoprefixer** back to its last version

**Comment by w0rm** [comment]
So you've installed Autoprefixer that works for PostCSS 8, but I haven't updated `gulp-postcss` yet. 
The update is captured in this issue: https://github.com/postcss/gulp-postcss/issues/161

**Comment by Alecto** [comment]
i use gulp-postcss 8.0 and have the same problem
![image](https://user-images.githubusercontent.com/8464662/94103043-3d68e980-fe3c-11ea-94c5-c488c07c74e2.png)

**Comment by w0rm** [comment]
@Alecto update gulp-postcss to 9.0.0 if you want to use PostCSS 8.0.0

**Comment by Andre741** [comment]
The issue unfortunately still persists
![Bildschirmfoto 2021-02-22 um 17 30 18](https://user-images.githubusercontent.com/13705759/108738191-a5c70e80-7533-11eb-8652-32f172acc157.png)

**Comment by Braintelligence** [comment]
I have the same issue. Could you fix it by now @Andre741 ?
