### ISSUE TITLE
Error: [object Object] is not a PostCSS plugin

### ISSUE THREAD

**Issue by billyromano** [postcss/gulp-postcss#167]
I started having this issue after upgrading `gulp-postcss@^9.0.0` and `autoprefixer@^10.0.1` plugins to the latest versions . The `npm i postcss` fix worked for me. I'm hoping the `gulp-postcss` package updates there reference for the `postcss` package, so we don't need to have 2 postcss plugins installed in our project dependencies.

**Comment by w0rm** [comment]
According to the [changelog](https://github.com/postcss/gulp-postcss#changelog), `postcss` has become a peer dependency. [The install instructions](https://github.com/postcss/gulp-postcss#install) include both `postcss` and `gulp-postcss`.

`gulp-postcss` is just a wrapper around `postcss` that runs it on each file from the gulp stream. `postcss` is the main project  that applies transformations from all postcss plugins, like `autoprefixer`.

I don't see any issue here. Please elaborate!
