### ISSUE TITLE
Error: PostCSS plugin autoprefixer requires PostCSS 8.

### ISSUE THREAD

**Issue by brendan8c** [postcss/gulp-postcss#174]
What am I doing wrong? Please tell me. Why does it require version 8? You have already released version 9.
I use: 
"gulp-sourcemaps": "^3.0.0",
"gulp-sass": "^4.1.0",
"gulp-postcss": "^9.0.0",
"gulp-autoprefixer": "^7.0.1",
"cssnano": "^5.0.5",
"gulp-concat": "^2.6.1",

![2021-05-31 21_13_06-● gulpfile js - start_gulp - Visual Studio Code  Не поддерживается](https://user-images.githubusercontent.com/61526280/120229308-82f47680-c255-11eb-96d9-4ca63e0247dc.png)
![2021-05-31 21_17_55-package json - start_gulp - Visual Studio Code  Не поддерживается](https://user-images.githubusercontent.com/61526280/120229450-d8c91e80-c255-11eb-9747-cbb1a3c539a5.png)

```
[21:09:10] Starting 'html'...
[21:09:10] Finished 'html' after 100 ms
[21:09:10] Starting 'scss'...
[21:09:11] 'scss' errored after 249 ms
[21:09:11] Error in plugin "gulp-postcss"
Message:
    PostCSS plugin autoprefixer requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
Details:
    fileName: D:\Projects\Dev\start_gulp\app\scss\style.css
    domainEmitter: [object Object]
    domainThrown: false

Stack:
Error: PostCSS plugin autoprefixer requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (D:\Projects\Dev\start_gulp\node_modules\postcss\lib\processor.js:153:15)
    at new Processor (D:\Projects\Dev\start_gulp\node_modules\postcss\lib\processor.js:56:25)
    at postcss (D:\Projects\Dev\start_gulp\node_modules\postcss\lib\postcss.js:55:10)
    at D:\Projects\Dev\start_gulp\node_modules\gulp-postcss\index.js:50:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[21:09:11] 'build' errored after 388 ms
```

I want to connect the following collaboration plugins to gulp: cssnano, autoprefixer and gulp-postcss.

**Comment by w0rm** [comment]
Hi! According to the migration guide (the link from the error message) you need to add postcss to your dependencies. Also, I believe you need to install autoprefixer as postcss plugin, not gulp plugin.

**Comment by brendan8c** [comment]
Thank you w0rm! 
I have installed `"postcss": "^8.3.0"` and replaced `"gulp-autoprefixer": "^7.0.1"` with `"autoprefixer": "^10.2.6"`.
Now it works! 👍

**Comment by w0rm** [comment]
@brendan8c you’re welcome!
