### ISSUE TITLE
Outputing multi-level folders

### ISSUE THREAD

**Issue by Ryan-da-ghost** [postcss/gulp-postcss#175]
Here is my gulp file: 
```js
var gulp = require("gulp");
var postcss = require("gulp-postcss");
var autoprefixer = require("autoprefixer");
var cssnano = require("cssnano");
var precss = require("precss");
var gulp = require("gulp");
var browserSync = require("browser-sync").create();

gulp.task("css", function () {
  var plugins = [autoprefixer, cssnano, precss];
  return gulp
    .src("./assets/styles/*")
    .pipe(postcss(plugins))
    .pipe(gulp.dest("./assets/output/"));
});
```
My css folder 
--- styles
 ---- base
 ---- layouts
 ---- abstarcts
-- style.css
postcss only outputs the style.css file can someone help mee?  i tried a lot of stuff but nothing is working

**Comment by w0rm** [comment]
According to your description “style.css” is the only file that is matched by the glob pattern "./assets/styles/*". 

You can read about globs here https://gulpjs.com/docs/en/getting-started/explaining-globs
