### ISSUE TITLE
Why does the new version 9.1.0 not comply with semver about engines.node?

### ISSUE THREAD

**Issue by shiftj18** [postcss/gulp-postcss#188]
![image](https://github.com/postcss/gulp-postcss/assets/8348072/08e5e64f-6bdb-478c-aea5-eab71056a0e4)

![image](https://github.com/postcss/gulp-postcss/assets/8348072/80f2e682-a453-4e94-a104-81e7dbe5da77)

![image](https://github.com/postcss/gulp-postcss/assets/8348072/f3297307-0882-40b5-a929-8b7019e2894c)

**Comment by shiftj18** [comment]
Shouldn't the node version be compatible with the `x` of the semver rule?

This causes packages or apps using the '^9.0.1' version to abort unexpectedly, when installed using the `yarn`(v1) package manager in an earlier version of the node environment. Eventually, the installation failed, and the directory 'node_modules' is not exists.

```bash
"error gulp-postcss@9.1.0: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.15.0" error Found incompatible module.'
```

**Comment by shiftj18** [comment]
![image](https://github.com/postcss/gulp-postcss/assets/8348072/0b9fd27e-9f02-42b3-81e7-167a2dec77de)

**Comment by shiftj18** [comment]
> Hey @shiftj18. No particular reason. An oversight on my side.

Can you fix it?

Rollback `latest` to 9.0.1, and deprecated 9.1.0.

Then, use the major version to carry the 16 to 18 changes to 'engines.node', like 10.0.0.

**Comment by w0rm** [comment]
I’m afraid somebody may already be depending on the new functionality in 9.1.0. Maybe we could release 9.2.0 that roll backs the changes to 9.0.1 and then 10.0.0 that includes the new changes?

**Comment by w0rm** [comment]
@shiftj18 I will try do as you’ve suggested. Seems reasonable to me

**Comment by w0rm** [comment]
@shiftj18 done! Thanks for reporting
