### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by paazmaya** [postcss/gulp-postcss#33]
Please tag the releases which have been pushed to npm, in order to make it easier to see what are the differences between each release.
Tagging could be done for example:

```sh
git tag v5.1.1 1245750bfcd800b6d913224b2ccfa51725da63aa
```

**Comment by ai** [comment]
BTW, all my PostCSS projects has a tags for releases. I also signed it with my GPG key because I am cryptomaniac :).

**Comment by w0rm** [comment]
Done
