### ISSUE TITLE
Clean up error hangling

### ISSUE THREAD

**Issue by ai** [postcss/gulp-postcss#34]
In PostCSS 4.1.6 parsing error uses Promise reject event too. So you can clean code: https://github.com/postcss/postcss-loader/commit/dc45577ea80b0ea868248dfa600befcb400ca532

@w0rm do not afraid to ask me about better API for your plugin next time :).

**Comment by w0rm** [comment]
Does `postcss(plugins)` work now with object plugins? I had to revert back because of this https://github.com/postcss/gulp-postcss/commit/564c2dbab8bd3cb1cda8698195239ce3aaf8eeae

**Comment by w0rm** [comment]
@ai It is not working, test https://github.com/postcss/gulp-postcss/blob/master/test.js#L11 is failing

**Comment by ai** [comment]
@w0rm like this one? https://github.com/postcss/postcss/commit/57a8d4fa771fbca9f4976f586b455545f87f21f4

**Comment by w0rm** [comment]
Yeah, this will simplify api

**Comment by ai** [comment]
OK. I finish dependencies updating and will publish release

**Comment by ai** [comment]
Released in 4.1.8
