### ISSUE TITLE
Add Sass encoding note

### ISSUE THREAD

**Issue by ai** [postcss/gulp-postcss#39]
Add note, that Sass has a issuue with Unicode and `@encoding` https://github.com/postcss/autoprefixer/issues/430

**Comment by ai** [comment]
Here is more relevant information: https://github.com/postcss/postcss/issues/308

**Comment by w0rm** [comment]
[This issue](https://github.com/sass/libsass/issues/879) has been [fixed in libsass v3.2.0](https://github.com/sass/libsass/releases/tag/3.2.0)
