### ISSUE TITLE
How about exemplifying error handling in the Readme?

### ISSUE THREAD

**Issue by davidtheclark** [postcss/gulp-postcss#41]
The confusion in #32 is legitimate, I think, given that users would expect runners to show errors without additional configuration. Since it looks like the solution is the use gulp-plumber or `.on('error', ..)`, maybe it would reduce confusion to exemplify this in the Readme and point out its importance. What do you think?

**Comment by w0rm** [comment]
@davidtheclark it seems that there is a bug: handling error from inside `promise.then` callback suppresses stream’s uhnandled exception from being output in console. But I really don't know how to fix this.

**Comment by w0rm** [comment]
@davidtheclark I have managed to fix #32, do you think this issue is still relevant? What should be added in the Readme?

**Comment by davidtheclark** [comment]
Nice job. I think it works now exactly how a person should expect, so I don't think anything needs to be added.
