### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by christiananguiano** [postcss/gulp-postcss#43]
I get the error: 
`TypeError: undefined is not a function`
Whenever I try using cssnext. I'm not sure if this is an issue with gulp-postcss or with cssnext, but the log leads me to believe it is a problem with gulp-postcss.

This is my gulpfile:

    var gulp = require("gulp");
    var postcss = require("gulp-postcss");
    var cssnext = require("cssnext");

    gulp.task("css", function () {
      var processors = [
        cssnext()
      ];

      return gulp.src("main.css")
        .pipe(postcss(processors))
        .pipe(gulp.dest("css/"));
    });

And this is the output of running `gulp css`:

    [14:06:27] Using gulpfile ~/Desktop/postcss-test/gulpfile.js
    [14:06:27] Starting 'css'...

    events.js:85
          throw er; // Unhandled 'error' event
                ^
    TypeError: undefined is not a function
    at LazyResult.run (/Users/Christian/Desktop/postcss-test/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:193:24)
    at /Users/Christian/Desktop/postcss-test/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:107:37
    at LazyResult.asyncTick (/Users/Christian/Desktop/postcss-test/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:120:15)
    at /Users/Christian/Desktop/postcss-test/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:118:27
    at LazyResult.asyncTick (/Users/Christian/Desktop/postcss-test/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:120:15)
    at /Users/Christian/Desktop/postcss-test/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:118:27
    at LazyResult.asyncTick (/Users/Christian/Desktop/postcss-test/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:120:15)
    at /Users/Christian/Desktop/postcss-test/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:118:27
    at LazyResult.asyncTick (/Users/Christian/Desktop/postcss-test/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:120:15)
    at /Users/Christian/Desktop/postcss-test/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:118:27

**Comment by wesbos** [comment]
This is because your list of processors should be the module name, in yours you are calling it with `()`

```
  var processors = [
    cssnext
  ];
```

That said - I came here looking for a solution because this exact setup isn't actually converting my CSS with cssnext

**Comment by wesbos** [comment]
Wait - your might be right. But this works for me:

```
/* jshint asi: true */

'use strict';

var gulp = require( 'gulp' );
var postcss = require( 'gulp-postcss' );
var cssnext = require( 'cssnext' );
var autoprefixer = require('autoprefixer-core');

gulp.task( 'css', function() {
    gulp.src( 'css-next.css' )
        .pipe( postcss([cssnext(), autoprefixer]) )
        .pipe( gulp.dest( 'build/' ) )
} );

```

**Comment by christiananguiano** [comment]
Weird, I get the exact same error when using your exact same code.

**Comment by christiananguiano** [comment]
So I decided to reinstall node and npm using the official package from their website and it is now working. I used nvm before. Don't know why it wouldn't work with nvm's version.
