### ISSUE TITLE
gulp-postcss silently catch all errors in other pipes

### ISSUE THREAD

**Issue by Splurov** [postcss/gulp-postcss#45]
How to reproduce:
```bash
$ git clone git@github.com:Splurov/gulp-postcss-errors-bug.git
$ npm install
$ gulp test
```
Task done, but actually it's failed due to throw: https://github.com/Splurov/gulp-postcss-errors-bug/blob/master/gulpfile.js#L11
Now, comment line 9 https://github.com/Splurov/gulp-postcss-errors-bug/blob/master/gulpfile.js#L9 and we have an exception, as it should be.
If we comment a throw on line 11 the task will be executed successfully.

I think gulp-postcss pipe should not affect any other pipes and should not silent any exceptions.

**Comment by w0rm** [comment]
@Splurov should be fixed now.

**Comment by Splurov** [comment]
Fixed, thank you. Please don't forget to publish new version to npm.

**Comment by w0rm** [comment]
@Splurov sorry, I forgot to publish it yesterday, should be published now.
