### ISSUE TITLE
So, how does one integrate gulp-ruby-sass into this flow?

### ISSUE THREAD

**Issue by smlombardi** [postcss/gulp-postcss#48]
Can you please provide an example?  I have tried, yet failed every time.

**Comment by TrySound** [comment]
@smlombardi Show log. Show build code.

**Comment by smlombardi** [comment]
Please see https://stackoverflow.com/questions/31944848/trying-to-integrate-gulp-sass-with-gulp-autoprefixer-postcss-failing-miserably

**Comment by TrySound** [comment]
@smlombardi Try this
```js
gulp.task('style', function(done) {
  return sass('source', { sourcemap: true })
    .on('error', done)
    .pipe(postcss([autoprefixer({
      browsers: ['last 2 versions']
    })]))
    .on('error', done)
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('result'))
    .pipe(reload({ stream: true }));
});
```

**Comment by TrySound** [comment]
@smlombardi But if you start new project try to use postcss alternative like [precss](https://github.com/jonathantneal/precss) or [cssnext](https://github.com/cssnext/cssnext). You can also combain different plugins and use cssnext with nested.

**Comment by smlombardi** [comment]
I get this with the above code:

````
STARYU:designsystem stevelombardi$ gulp style
[13:54:31] Using gulpfile ~/Documents/designsystem/gulpfile.js
[13:54:31] Starting 'style'...
[13:54:32] gulp-ruby-sass stdout: directory
[13:54:32] gulp-ruby-sass stdout: write design_system.css
      write design_system.css.map
[13:54:32] gulp-ruby-sass stdout: write live_preview.css
      write live_preview.css.map
[13:54:33] 'style' errored after 1.03 s
[13:54:33] TypeError in plugin 'gulp-postcss'
Message:
    object is not a function
STARYU:designsystem stevelombardi$ 
````

**Comment by rstuart85** [comment]
I can this same error with the same workflow. Any idea's what is happening here?

**Comment by rstuart85** [comment]
For what it is worth, if you remove autoprefixer as a postprocessor, it seems to work.

**Comment by TrySound** [comment]
@smlombardi @rstuart85  Show whole code

**Comment by rstuart85** [comment]
Fix posted on the stackoverflow question. Essentially, it seems to be down to which package you are using autoprefixer from. This doesn't work (produces the error described):

    var autoprefixer = require('gulp-autoprefixer');

This does work (no more error):

    var autoprefixer = require('autoprefixer-core');

That's all you need to change. You can test with the code posted above.
