### ISSUE TITLE
Depracated dependencies info appearing during the first scss->css compile while using gulp

### ISSUE THREAD

**Issue by matchabros** [postcss/gulp-postcss#52]
It appears only at the very first compile which takes the longest.
I noticed that the log appears for every single postcss plugin I use (lostgrid and autoprefixer in my example), I use the latest release of gulp-postcss.

```
Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#removeSelf is deprecated. Use Node#remove.
Container#eachRule is deprecated. Use Container#walkRules instead.
Node#style() is deprecated. Use Node#raw()
Node#before is deprecated. Use Node#raws.before
Node#_value was deprecated. Use Node#raws.value
```

**Comment by ai** [comment]
It is not issue of `gulp-postcss`. It is warnings for many PostCSS plugins, which use deprecated PostCSS 4.x API.

The best way is just a create `go to PostCSS 5.0 API` issues in every plugin that you use. Or just wait for few weeks, everyone will migrate.

**Comment by matchabros** [comment]
I see, thanks for clarifying.
