### ISSUE TITLE
browsers: ['not Chrome'] throws an error

### ISSUE THREAD

**Issue by JeffreyArts** [postcss/gulp-postcss#54]
I get an error when I want to target all browsers. The browser query I am using is as followed:

BrowserslistError: Unknown browser query `Chrome`

I solved it already by changing the query to ['last 99 versions'] but I thought is was worth mentioning either way :)

**Comment by ai** [comment]
It has no connection with `gulp-postcss`, because it is Browserslist error, which is used in Autoprefixer in many PostCSS plugins. You can get it by `BrowserslistError`.

**Comment by ai** [comment]
So you need to open [Browserslist docs](https://github.com/ai/browserslist) and read what browsers options is avaiable. You can find there that there is no such option as `Chrome`. You always must set version.
