### ISSUE TITLE
Problem with Node v4.0.0 after upgrading to gulp-postcss 6.0.0

### ISSUE THREAD

**Issue by pensierinmusica** [postcss/gulp-postcss#55]
Hi,

I recently installed Node v4.0.0 on my system, then after upgrading `gulp-postcss` to 6.0.0 the process exits with this error message:

>Your current PostCSS version is 5.0.4, but postcss-custom-media uses 4.1.16. Perhaps this is the source of the error below.

Any idea what might be causing the problem? Thanks!

**Comment by w0rm** [comment]
postcss-custom-media plugin wants an older postcss version, however the recent gulp-postcss uses the recent one. Try to update  postcss-custom-media

**Comment by pensierinmusica** [comment]
Oh, I think the bug is actually caused by this then: https://github.com/cssnext/cssnext/issues/202

Thanks

**Comment by MoOx** [comment]
It's not "a bug", it's a warning :)
