### ISSUE TITLE
TypeError in plugin 'gulp-postcss' Message:     Cannot read property 'before' of undefined

### ISSUE THREAD

**Issue by jamesscholeyweb** [postcss/gulp-postcss#57]
Still getting this error when using @import with latest versions of gulp-postcss and cssnext.

I was under the impression postcss-import and most plugins were up to speed with the new version now? Just going round in circles on github trying to work out where the problem lies. But as the error is thrown as gulp-postcss plugin. I'm raising the issue here.

Thanks in advance

**Comment by TrySound** [comment]
@jamesscholeyweb cssnext uses old postcss api. U can install gulp-postcss5 and use postcss4 compatible versions of the other plugins.

**Comment by jamesscholeyweb** [comment]
@TrySound Thanks Bogdan, am I right in thinking that cssnext is just a collection of postcss plugins? I could achieve the same result bringing in the plugins I require alone?

**Comment by TrySound** [comment]
@jamesscholeyweb You are right. But if not all plugins use new api you will get some deprecations warnings. Errored was only postcss-import.

**Comment by jamesscholeyweb** [comment]
@TrySound Well latest postcss-import works fine with the 5.0 api, so I'll just build in what I require. What I don't understand is if cssnext is just a collection of modules to accompany postcss why they don't just pull in the latest versions on install? Anyway I have it working as I require with latest version of postcss and import. Thanks Bogdan

**Comment by TrySound** [comment]
@jamesscholeyweb This uses new api) https://github.com/cssnext/postcss-cssnext

**Comment by jamesscholeyweb** [comment]
@TrySound Well that explains everything :)
