### ISSUE TITLE
Process inline CSS in HTML using PostCSS

### ISSUE THREAD

**Issue by pensierinmusica** [postcss/gulp-postcss#61]
It would be great if `gulp-postcss` could process CSS within HTML files too, for the reasons mentioned in https://github.com/postcss/postcss/issues/596.

Do you think this could be implemented?

Looking forward to hear your thoughts!

Cheers  :)

**Comment by ai** [comment]
Maybe we should have gulp-html-postcss in order of UNIX way?

**Comment by pensierinmusica** [comment]
Huh, it looks like it exists already... https://github.com/StartPolymer/gulp-html-postcss

Sorry for not noticing it earlier  ;)

Could you take a quick look and see if all we need is already there?

**Comment by w0rm** [comment]
I agree that this is a use case that gulp-postcss should not solve, because it is meant to work only with css files.
