### ISSUE TITLE
problem in a package using postcss

### ISSUE THREAD

**Issue by leandroruel** [postcss/gulp-postcss#62]
output of my terminal:

/var/www/vecchio/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:152
        this.processing = new Promise(function (resolve, reject) {
                              ^
ReferenceError: Promise is not defined

**Comment by leandroruel** [comment]
solved!!

solution: http://stackoverflow.com/questions/32490328/gulp-autoprefixer-throwing-referenceerror-promise-is-not-defined

**Comment by w0rm** [comment]
@leandroruel I would suggest to update the node version if this is possible, because yours seems to be "slightly" outdated. Promise was introduced since 0.12, and the current stable version is 5.0.0, although we're still using 4.2.1 at work.
