### ISSUE TITLE
Impossible to force "disable sourcemaps"

### ISSUE THREAD

**Issue by rvock** [postcss/gulp-postcss#65]
It is impossible to tell postcss to forcibly disable sourcemap support:
```js
var ieFilter = gulpFilter(['main.css'], {restore: true});

gulp.src('**/*.css')
	.pipe(sourcemaps.init())
	.pipe(postcss([autoprefixer]))
	.pipe(sourcemaps.write('.'))
	.pipe(gulp.dest(paths.staticBasePath))
	.pipe(ieFilter)
	.pipe(postcss([postcssIE8], {map: false}))
	.pipe(rename({extname: '-ie.css'}))
	.pipe(gulp.dest(paths.staticBasePath));
```

This throws an error. I am not quite sure if this is a problem of gulp-sourcemaps or gulp-postcss. But when I change the map-generation in gulp-postcss/index.js it works correctly:
```js
if (file.sourceMap && (!options || options.map !== false)) {
```

**Comment by rvock** [comment]
I just found a gulp plugin which fixes this by removing the file.sourceMap property of all files in the stream:
[gulp-purge-sourcemaps](https://github.com/stipsan/gulp-purge-sourcemaps)

So after writing to dest, I just need to call purgeSourcemaps
```js
.pipe(gulp.dest(paths.staticBasePath))
.pipe(purgeSourcemaps())
```

**Comment by w0rm** [comment]
@rvock thanks for discovering this issue and how to fix it. Feel free to open pull request with a corresponding test case.

**Comment by w0rm** [comment]
Closing because it seems that the feature is not needed.
