### ISSUE TITLE
How to split a css file into multiple

### ISSUE THREAD

**Issue by matthewrobb** [postcss/gulp-postcss#67]
I have been digging for hours trying to find an example of a plugin that can output two files from a single source. I am at a loss and I am hoping I am simply overlooking something obvious.

It appears as though right now there is a hard assumption that `1:1` for from-file:to-file where as I am hoping to find a way to do `1:n+1`. Any help would be greatly appreciated!

**Comment by w0rm** [comment]
@matthewrobb postcss has only one output, therefore there can be only one output from gulp-postcss.

**Comment by miljkovicmisa** [comment]
Maybe a usecase would be a larger application that the final output file exceeds 1mb? I am using a framework (foundation) for base css and multiple files for landing pages with differrent styles, it would be nice to separate the output into multiple files [base.css, landing-page-1.css, landing-page-2.css, etc....] that way i could load `base.css` alongside any other stylesheets in my html.
