### ISSUE TITLE
Log messages

### ISSUE THREAD

**Issue by thejameskyle** [postcss/gulp-postcss#68]
There doesn't appear to be anyway to get access to `result.messages` as `result` isn't exposed anywhere.

This makes integrating tools like cssstats difficult because [it just pushes to `messages`](https://github.com/cssstats/cssstats-core#postcss-plugin)
```js
postcss().use(cssstats()).process(css).then(function (result) {
  result.messages.forEach(function (message) {
    console.log(message)
  })
})
```

Am I missing something or is this just not possible now?

**Comment by TrySound** [comment]
@thejameskyle Warnings are already shown
https://github.com/postcss/gulp-postcss/blob/master/index.js#L63-L65

**Comment by w0rm** [comment]
@thejameskyle please elaborate, in your example I see postcss itself, while this project is a postcss plugin for gulp.

[gulp-postcss logs all messages to console](https://github.com/postcss/gulp-postcss/blob/master/index.js#L49).

**Comment by w0rm** [comment]
`result` object is not exposed from gulp-postcss and I don't think it should be. What you can do, is add a [reporter plugin](https://github.com/postcss/postcss-reporter) that will output all messages, and not just warnings.

**Comment by thejameskyle** [comment]
Neither gulp-postcss or postcss-reporter logs anything from cssstats to the console. Unless I am missing something here: https://github.com/thejameskyle/__postcss-log-messages

**Comment by w0rm** [comment]
@thejameskyle gulp-postcss only logs `result.warnings()`. Thanks for the example, I will check why postcss-reporter doesn't output messages.

**Comment by w0rm** [comment]
@thejameskyle  try this:

```
var gulp = require('gulp');
var postcss = require('gulp-postcss');

gulp.task('build', function() {
  return gulp.src('input.css').pipe(postcss([
    require('cssstats')(),
    require('postcss-reporter')({
      plugins: ['postcss-cssstats'],
      formatter: function (input) {
        var stats = input.messages.find(
          function (message) {
            return message.type == 'cssstats';
          }
        );
        return JSON.stringify(stats.stats, 2, 2);
      }
    })
  ]));
});
```

**Comment by w0rm** [comment]
@thejameskyle the reason its this complicated is how the message is logged, it has a custom type and `stats`  is an object. Thats why reporter doesn't understand it out of box.

**Comment by thejameskyle** [comment]
Why shouldn't the postcss gulp plugin expose `result` in the same way, this solution is relying on a lot of knowledge about the ecosystem of postcss plugins when there doesn't appear any reason to do that.

**Comment by w0rm** [comment]
@thejameskyle instead of postcss-reporter, you can put your `function (root, result) {}`

**Comment by w0rm** [comment]
@thejameskyle sorry I didn't have enough time to explain my thoughts yesterday!

gulp works with file objects, it should share nothing else between plugins. Some extra things hacked into file object e.g. sourcemaps already make everything quite complicated. I really don't want internals of postcss to be exposed anyhow, so you'd better log custom messages from within postcss. Just add a simple function plugin, that will not modify css, but simply log a message that you need from cssstats.

```javascript
var gulp = require('gulp');
var postcss = require('gulp-postcss');

gulp.task('build', function() {
  return gulp.src('input.css').pipe(postcss([
    require('cssstats')(),
    function (css, input) {
      var stats = input.messages.find(
        function (message) {
          return message.type == 'cssstats';
        }
      );
      if (stats) {
        console.log(JSON.stringify(stats.stats, null, 2));
      }
    }
  ]));
});
```

**Comment by thejameskyle** [comment]
Thank you that was very helpful
