### ISSUE TITLE
syntax: scss can't work

### ISSUE THREAD

**Issue by fsy0718** [postcss/gulp-postcss#69]
this's my gulp task
```
gulp.task('css', function() {
  var processors = [cssImport(),customProperties(),alias,crip()];
   return gulp.src(sourceDir + '/postcss/*.pcss')
    .pipe(postcss(processors, {syntax : scss}))
   .pipe(rename({
     suffix: '-postcss',
     extname: '.css'
    }))`
    .pipe(gulp.dest(targetDir + '/css'));
});
```
this's my postcss file
```
//这是一个测试
body{
  color: red;
}
```
when I complete the task, the inline-comment  still exists

```
//这是一个测试

body{
  color: red;
}```

**Comment by TrySound** [comment]
@fsy0718 Syntax mean scss-in and scss-out. If you want to use css stringifier use `parser` option instead of `syntax`.

**Comment by fsy0718** [comment]
thanks, when I use `parser` option instead of `syntax`, If the same file is in force, but if postcss-import imported file is invalid

**Comment by TrySound** [comment]
@fsy0718 Current release of import do not support syntax and parser options. They are implemented in dev branch. We will make a release asap. But not today :)

**Comment by TrySound** [comment]
You can try this for now
https://github.com/jonathantneal/postcss-partial-import

**Comment by fsy0718** [comment]
Thank you, `postcss-partial-import` module can achieve a very good effect
