### ISSUE TITLE
.css:1:1: Unknown word

### ISSUE THREAD

**Issue by knynkwl** [postcss/gulp-postcss#72]
I am getting an `Unknown word` error for `//` comments 

```
Error in plugin 'gulp-postcss'
Message:
postcss-import:style.css:1:1: Unknown word

// Comment
^ 
```

**Comment by TrySound** [comment]
@knynkwl css support only `/* comment */` format. If you want to use `//` use different syntax like [postcss-scss](https://github.com/postcss/postcss-scss).

**Comment by knynkwl** [comment]
ah, right thx
