### ISSUE TITLE
Getting 'Unknown word' font import

### ISSUE THREAD

**Issue by PhilRedm** [postcss/gulp-postcss#73]
I get the following error:

```Error: postcss-import-url: <css input>:1:1: Unknown word```

when the following import is included in my source:

```@import url("//hello.myfonts.net/count/3022f1");```

Any advise to get round this error?

**Comment by TrySound** [comment]
@PhilRedm It's [postcss-import-url](https://github.com/unlight/postcss-import-url) problem. Report this issue there.
