### ISSUE TITLE
cssnext: autoprefixer duplicate. readme example

### ISSUE THREAD

**Issue by Zougi** [postcss/gulp-postcss#76]
Hello, I'm having trouble understanding the example given in the readme regarding cssnext and autoprefixer.

cssnext already comes with autoprefixer (look at their package.json).
so in the example
    var processors = [
        autoprefixer({browsers: ['last 1 version']}),
        opacity,
        cssnext()
    ];

it should be:
    var processors = [
        opacity,
        cssnext({browsers: ['last 1 version']})
    ];

am I right? http://cssnext.io/usage/

Maybe cssnext should not include autoprefixer now it joined postcss. However example stays incorrect. Right?

**Comment by TrySound** [comment]
@Zougi Use only postcss-cssnext and set browsers option. It's not gulp-postcss issue. You are able to control your plugins.

**Comment by ai** [comment]
cssnext is a plugin pack. It contains many PostCSS plugins. And cssnext contains Autoprefixer too. So right now you have two Autoprefixers and your build process is slower.

Cssnext suggests you, that you could remove first Autoprefixer.

**Comment by MoOx** [comment]
Imo there is a major issue in the README as it show wrong example that everyone takes as good examples. That may be the reason why 99% of postcss tutorial are wrong.

**Comment by ai** [comment]
@MoOx good point!

**Comment by Zougi** [comment]
Thanks for reopenning the issue. As I started and ended my report, readme got me confused

**Comment by w0rm** [comment]
Fixed in #77
