### ISSUE TITLE
How to use px2rem.generateThree()?

### ISSUE THREAD

**Issue by cocca883** [postcss/gulp-postcss#82]
How to use px2rem.generateThree()?

.selector {
    width: 150px;
    height: 64px; /*px*/
    font-size: 28px; /*px*/
    border: 1px solid #ddd; /*no*/
}
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
.selector {
    width: 2rem;
    border: 1px solid #ddd;
}
[data-dpr="1"] .selector {
    height: 32px;
    font-size: 14px;
}
[data-dpr="2"] .selector {
    height: 64px;
    font-size: 28px;
}
[data-dpr="3"] .selector {
    height: 96px;
    font-size: 42px;
}

**Comment by w0rm** [comment]
Check the readme how to pass postcss loaders to gulp-postcss, I guess px2rem is one of them. For the loader features, this might not be the place to ask.
