### ISSUE TITLE
Support of postcss v.5.1.0

### ISSUE THREAD

**Issue by p-ivannikov** [postcss/gulp-postcss#85]
Hi there. Today i'm got issue with [stylelint](https://github.com/stylelint/stylelint) plugin for postcss. It uses postcss v.5.1.0. When you planning to add support of new version PostCSS? 

Message from log
> Your current PostCSS version is 5.0.14, but stylelint uses 5.1.0. Perhaps this is the source of the error below.

**Comment by gucong3000** [comment]
I just try postcss v.5.1.0. It is work well with `gulp-postcss`.
```bash
npm i --save-dev postcss
```

**Comment by TrySound** [comment]
@p-ivannikov Just reinstall your node_modules.

**Comment by p-ivannikov** [comment]
thanks guys
