### ISSUE TITLE
not combining multiple css files?

### ISSUE THREAD

**Issue by noahehall** [postcss/gulp-postcss#86]
i have this code:
gulp.task('css', function () {
    var processors = [
        precss(),
        autoprefixer({browsers: ['last 2 version']}),
        cssmodules()
    ];
    return gulp.src('./src/**/*.css')
        .pipe(postcss(processors))
        .pipe(rename('bundle.css'))
        .pipe(gulp.dest('./src/public/css'))
});

it only takes the first css file and creates a bundle.css out of it

How do i make it find all css files, concat, and then take bundle css?

**Comment by noahehall** [comment]
I was able to use gulp-concat

heres working code:
gulp.task('css', function () {
    var processors = [
        precss(),
        autoprefixer({browsers: ['last 2 version']}),
        cssmodules()
    ];

    return gulp.src('./src/**/*.css')
        .pipe(concat("bundle.css"))
        .pipe(postcss(processors))
        .pipe(gulp.dest('./src/public/css'))
});

**Comment by TrySound** [comment]
@noahehall https://github.com/contra/gulp-concat

**Comment by w0rm** [comment]
@noahehall what @TrySound said.
