### ISSUE TITLE
better "to" auto detection based on expected dest()

### ISSUE THREAD

**Issue by sormy** [postcss/gulp-postcss#88]
I propose to change:

from:

```
opts.to = opts.to || file.path;
```

to:

```
opts.to = opts.to || (opts.dest ? path.join(opts.dest, file.relative) : file.path);
```

it could be used to get benefits from postcss-url when you need to process multiple files:

```
gulp.task('build-less', function() {
  return gulp
    .src([ 'src/**/*.less' ], { base: '.' })
    .pipe(sourcemaps.init('.'))
    .pipe(less())
    .pipe(postcss([
      url({ url: 'rebase' }),
      autoprefixer(config.autoprefixer)
    ],{ dest: '.tmp' }))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('.tmp'))
    .pipe(browserSync.stream({ match: '**/*.css' }));
});
```

**Comment by w0rm** [comment]
Sorry for the late response. But have you tried to achieve the same result with `gulp-rename` before piping to postcss? I am quite hesitant to add configuration magic in order to configure some plugin. I think options [should match postcss options](https://github.com/postcss/postcss#options).

**Comment by sormy** [comment]
The proposed magic allows to have `to` to be auto configured for array of files. It's not natural that plugin for gulp (which is actually designed to process array of files thru set of processors) is not designed to process more than one file.

**Comment by w0rm** [comment]
I don't see any problem in processing more than one file. It just looks that you want to configure a certain postcss plugin differently per each file, that is not a use case that should be covered by gulp-postcss. If we begin adjusting the configuration for different postcss plugins then it will be harder to support the project. Also, adding a configuration key to the same namespace as postcss options means it will be passed down to postcss as well. What if in the future postcss decides to reserve this option for something else?

Regarding your use case, I've checked the readme of the url plugin, it supports the url option as a function that will be executed for each occurrence. This can be used to implement any possible url transformation.

**Comment by sormy** [comment]
postss url rewrite plugin know nothing about source filename and can't rewrite urls well without knowledge of destination filename. Most of postcss plugins don't need that information, so they are working well with this plugin. But this plugin can't. This plugin assumes that postcss instance is configured well. But it is not. By default gulp-postcss don't pass any "to" to postcss instance. The only way to pass "to" is to hardcode value via "to" options to postcss-plugin, but that will work ONLY if you have ONE file in pipe. For multiple files there will different "to" and gulp-postcss have no options for that. 

Default `file.path` is **NOT** correct expected destination to be used as default for `to`. So it is defect of this plugin.

Moreover, even if we will use custom "url" function it will give us nothing about expected "to".

**Comment by w0rm** [comment]
@sormy why is `file.path` not correct? Gulp transforms file in place, so the file name should stay the same.

If you set `url` option to a function, you have enough information there for your custom code to figure how to transform the url: you have the original url that you want to transform, you have the full path to the original file, and you know the destination path, because it is constant for all files.

```js
function transformUrl(url, decl, from, dirname, to, options) {
    
}

gulp.task('css', function () {
    var processors = [
        url({url: transformUrl})
    ];
    return gulp.src('./src/*.css')
        .pipe(postcss(processors))
        .pipe(gulp.dest('./dest'));
});
```

**Comment by sormy** [comment]
Because `to` is destination filename and it should not be the same as source filename.
Even if `url()` function has `to` argument it is invalid due to wrong `to` passed to postcss from gulp-postcss. Only gulp stream knows real destination and this information is not passed to postcss.

**Comment by w0rm** [comment]
> Because `to` is destination filename and it should not be the same as source filename.

There is no such rule. 

The final destination is not known to gulp plugins, it's the constant value that is passed to `gulp.dest`, you can use the same const in the url function that should cover your use case. I don't see any problem here.

**Comment by sormy** [comment]
ok, postcss plugins which rely on `to` by default doesn't work due to bad `to` passed, need to use boilerplate to get plugins work well... No problem :-) Ok, i will not continue to loose my and your time and will just make a fork...

**Comment by w0rm** [comment]
Go ahead, it's all open source.
