### ISSUE TITLE
Option to watch only changed files

### ISSUE THREAD

**Issue by last-partizan** [postcss/gulp-postcss#90]
Hello, is there an option to rebuild only changed files?

Just now i'm using gulp with config like this:
```
var CSS_DIR = ['./src/sass/*.scss', '!./src/sass/_*.scss'];

gulp.task("dev:css:build", function(){
    return gulp.src(CSS_DIR)
        .pipe(postcss(post_processors, {
            syntax: scss,
        }))
        .pipe(rename({extname: ".css"}))
        .pipe(gulp.dest('../../static/css'));
});
gulp.task("dev:css", function(){
    gulp.watch(CSS_DIR[0], ["dev:css:build"]);
}); 
```

And after changing some file, it rebuilds all; Is there some magick that rebuilds only changed files? And rebuild dependent files when using "@import" and postcss-import ?

**Comment by TrySound** [comment]
@last-partizan Here's similar example with less.
https://gist.github.com/TrySound/59f346854dc699705dc9141824097fd4

**Comment by last-partizan** [comment]
Nice idea for filtering only changed files before less, thanks.

**Comment by w0rm** [comment]
I don't think such magic exists as there is no dependency tree in gulp. You should probably use [webpack with postcss loader](https://github.com/postcss/postcss-loader#with-postcss-import) that seems to have this ability.
