### ISSUE TITLE
I need a way to disable the error output

### ISSUE THREAD

**Issue by gucong3000** [postcss/gulp-postcss#93]
I don't like to show error in console. This will be very slow.
I like to use other plugins to replace this feature, such as [postcss-browser-reporter](https://github.com/postcss/postcss-browser-reporter)

``` javascript
gulp_postcss([
  require('other-plugin'),
  require('postcss-browser-reporter')
], {
  warn: false
})
```

**Comment by w0rm** [comment]
@gucong3000 you can noop gutil-log, e.g.

```
var gutil = require('gulp-util');
// ...
gutil.log = gutil.noop;
// or
gutil.log = function() { return this; };
```

I found in this thread: https://github.com/gulpjs/gulp/issues/492#issuecomment-44872077

**Comment by w0rm** [comment]
@gucong3000 I don't like suggested `warn` option, because `options` are meant to be postcss options and mixing them in the same namespace may cause potential conflicts in the future.

**Comment by w0rm** [comment]
Here are more ideas (I didn't check them though):

1. --silent option from gulp, this should suppress the output from gutil.log

2. patch `gutil.log`

```
var gutil = require('gulp-util');
var oldLog = gutil.log;
gutil.log = function (plugin) {
   if (plugin.indexOf('gulp-postcss') !== 0) {
      oldLog.apply(gutil, arguments);
   }
}
```

**Comment by gucong3000** [comment]
@w0rm I just need a option to disable error report, and use `postcss-reporter` or other plugin.
There is no more elegant way?

**Comment by TrySound** [comment]
@gucong3000 There's a way with clearMessages in postcss-reporter.

**Comment by equinusocio** [comment]
`clearAllMessages `

**Comment by w0rm** [comment]
@TrySound @equinusocio thanks
