### ISSUE TITLE
Test fail in master branch.

### ISSUE THREAD

**Issue by gucong3000** [postcss/gulp-postcss#94]
![yarn](https://cloud.githubusercontent.com/assets/156269/19335874/4782890e-9139-11e6-8157-46a519923e3b.png)

Build Jobs: https://travis-ci.org/gucong3000/gulp-postcss/builds/167229600

This is my suggestion:

https://github.com/postcss/gulp-postcss/pull/96/files#diff-1dd241c4cd3fd1dd89c570cee98b79ddR117

**Comment by gucong3000** [comment]
This is my suggestion:

https://github.com/postcss/gulp-postcss/blob/master/test.js#L117

```
    assert(/sourceMappingURL=data:application\/json;(?:charset=\w+;)?base64/.test(file.contents.toString()))
```

**Comment by gucong3000** [comment]
When I use [yarn](https://yarnpkg.com) packages, to install, it will also be the same fault.

**Comment by gucong3000** [comment]
This problem also has a certain probability of occurrence in `npm`, which is an example:
- https://travis-ci.org/gucong3000/gulp-postcss/jobs/167229601
- https://travis-ci.org/gucong3000/gulp-postcss/jobs/167239062

**Comment by w0rm** [comment]
@gucong3000 thanks, merged
