### ISSUE TITLE
The test case about warnings, does not cover the relevant features

### ISSUE THREAD

**Issue by gucong3000** [postcss/gulp-postcss#97]
The test case that display warnings content.

There's a spelling mistake: https://github.com/postcss/gulp-postcss/pull/98/files#diff-1dd241c4cd3fd1dd89c570cee98b79ddL264 
It should be `toString` instead of `toSting`.

Here forget to write `assert`, and there is no way to deal with the Windows path separator
https://github.com/postcss/gulp-postcss/pull/98/files#diff-1dd241c4cd3fd1dd89c570cee98b79ddL278

**Comment by w0rm** [comment]
@gucong3000 thanks for fixing this!
